function B = wedge(a)
% transforms a 6-vector A into a 4x4 matrix B such that
B = [ 0    -a(6)  a(5) a(1) ; ...
    a(6)   0    -a(4)  a(2) ; ...
    -a(5)  a(4)    0   a(3) ; ...
    0      0       0     0 ] ;
return