%--------------------------------------------------------------------------
% script to point to MATLAB libraries for dealing with .cine files (Phantom
% camera output)
%--------------------------------------------------------------------------
mFilePath = mfilename('fullpath') ;
[PhMatlabSDK_root,~,~] = fileparts(mFilePath) ;

sdkPath = fullfile(PhMatlabSDK_root,'PhMatlabSDK') ; 
addpath(sdkPath, ...
	[sdkPath '\Bin'], ...%[sdkPath '\Bin\win32', ...	
	[sdkPath '\Bin\x64'], ...
	[sdkPath '\Doc'], ...
	[sdkPath '\Doc\Phantom SDK Doc'], ...
	[sdkPath '\PhDemoMatlab'], ...
	[sdkPath '\PhDemoMatlab\CamInfoDlg'], ...
	[sdkPath '\PhMatlab'], ...
	[sdkPath '\PhMatlab\Constants'], ...
	[sdkPath '\PhMatlab\Inc'], ...
	[sdkPath '\PhMatlab\OOP'], ...
	[sdkPath '\PhMatlab\Other'], ...
	[sdkPath '\PhMatlab\Other\Utils'], ...
	[sdkPath '\PhMatlab\PhCon'], ...
	[sdkPath '\PhMatlab\PhFile'], ...
	[sdkPath '\PhMatlab\PhInt'], ...
	[sdkPath '\SimpleCineFileReader']) ;
