addpath('F:\lucaDesktop\PhMatlabSDK', ...
	'F:\lucaDesktop\PhMatlabSDK\Bin', ...%'F:\lucaDesktop\PhMatlabSDK\Bin\win32', ...	
	'F:\lucaDesktop\PhMatlabSDK\Bin\x64', ...
	'F:\lucaDesktop\PhMatlabSDK\Doc', ...
	'F:\lucaDesktop\PhMatlabSDK\Doc\Phantom SDK Doc', ...
	'F:\lucaDesktop\PhMatlabSDK\PhDemoMatlab', ...
	'F:\lucaDesktop\PhMatlabSDK\PhDemoMatlab\CamInfoDlg', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\Constants', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\Inc', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\OOP', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\Other', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\Other\Utils', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\PhCon', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\PhFile', ...
	'F:\lucaDesktop\PhMatlabSDK\PhMatlab\PhInt', ...
	'F:\lucaDesktop\PhMatlabSDK\SimpleCineFileReader') ;